// Os emojis comuns do teclado, separados por assunto e com palavras de busca em português.
// É uma lista escrita à mão de propósito: as bibliotecas prontas de emoji pesam megabytes e vêm em inglês.

export interface EmojiGroup {
  name: string;
  /** Emoji que representa o grupo na barra de atalhos. */
  icon: string;
  emojis: [char: string, keywords: string][];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: 'Rostos',
    icon: '😀',
    emojis: [
      ['😀', 'sorriso feliz alegre'],
      ['😃', 'sorriso feliz animado'],
      ['😄', 'sorriso feliz rindo'],
      ['😁', 'sorriso dentes feliz'],
      ['😆', 'rindo gargalhada'],
      ['😅', 'rindo suando alívio nervoso'],
      ['🤣', 'rolando de rir gargalhada chorando'],
      ['😂', 'chorando de rir lágrimas'],
      ['🙂', 'sorriso leve tranquilo'],
      ['🙃', 'de cabeça para baixo ironia sarcasmo'],
      ['😉', 'piscada flerte'],
      ['😊', 'feliz tímido fofo'],
      ['😇', 'anjo santo inocente'],
      ['🥰', 'apaixonado corações amor'],
      ['😍', 'apaixonado olhos de coração amor'],
      ['😘', 'beijo mandando beijo'],
      ['😗', 'beijo'],
      ['😙', 'beijo sorrindo'],
      ['😋', 'delícia gostoso língua'],
      ['😛', 'língua brincadeira'],
      ['😜', 'língua piscada brincadeira'],
      ['🤪', 'maluco doido'],
      ['🤨', 'sobrancelha desconfiado duvidando'],
      ['🧐', 'monóculo analisando'],
      ['🤓', 'nerd óculos'],
      ['😎', 'óculos escuros estiloso legal'],
      ['🥳', 'festa comemorando aniversário'],
      ['😏', 'malicioso sorriso de canto'],
      ['😒', 'entediado sem graça mal-humorado'],
      ['😞', 'decepcionado triste'],
      ['😔', 'triste pensativo'],
      ['😟', 'preocupado'],
      ['😕', 'confuso'],
      ['🙁', 'triste leve'],
      ['😣', 'perseverando aflito'],
      ['😖', 'aflito confuso'],
      ['😫', 'cansado exausto'],
      ['😩', 'cansado chateado'],
      ['🥺', 'pidão carinha de pena implorando'],
      ['😢', 'chorando triste lágrima'],
      ['😭', 'chorando muito choro'],
      ['😤', 'bufando irritado determinado'],
      ['😠', 'bravo irritado'],
      ['😡', 'furioso raiva bravo vermelho'],
      ['🤬', 'xingando palavrão raiva'],
      ['🤯', 'explodindo cabeça chocado'],
      ['😳', 'chocado envergonhado corado'],
      ['🥵', 'calor quente derretendo'],
      ['🥶', 'frio congelando'],
      ['😱', 'gritando medo susto'],
      ['😨', 'assustado medo'],
      ['😰', 'ansioso suando medo'],
      ['😥', 'aliviado triste'],
      ['😓', 'suando decepcionado'],
      ['🤗', 'abraço abraçando'],
      ['🤔', 'pensando dúvida hmm'],
      ['🤭', 'ops tapando a boca risada'],
      ['🤫', 'silêncio shh segredo'],
      ['🤥', 'mentira pinóquio'],
      ['😶', 'sem boca calado'],
      ['😐', 'neutro sem expressão'],
      ['😑', 'sem expressão impaciente'],
      ['😬', 'sem graça constrangido careta'],
      ['🙄', 'revirando os olhos tédio'],
      ['😯', 'surpreso'],
      ['😦', 'assustado boca aberta'],
      ['😮', 'boca aberta uau surpreso'],
      ['😲', 'chocado pasmo'],
      ['🥱', 'bocejo sono entediado'],
      ['😴', 'dormindo sono zzz'],
      ['🤤', 'babando'],
      ['😪', 'sono cansado'],
      ['😵', 'tonto zonzo'],
      ['🤐', 'boca fechada zíper calado'],
      ['🥴', 'bêbado zonzo'],
      ['🤢', 'enjoado nojo'],
      ['🤮', 'vomitando passando mal'],
      ['🤧', 'espirro resfriado'],
      ['😷', 'máscara doente'],
      ['🤒', 'febre doente termômetro'],
      ['🤕', 'machucado curativo'],
      ['🤑', 'dinheiro cifrão rico'],
      ['🤠', 'caubói chapéu'],
      ['😈', 'diabo travesso'],
      ['👿', 'diabo bravo'],
      ['💀', 'caveira morto morri'],
      ['👻', 'fantasma assombração'],
      ['👽', 'alienígena et'],
      ['🤖', 'robô'],
      ['🤡', 'palhaço'],
      ['💩', 'cocô merda'],
    ],
  },
  {
    name: 'Gestos e pessoas',
    icon: '👍',
    emojis: [
      ['👍', 'joinha positivo curtir like ok'],
      ['👎', 'negativo não gostei deslike'],
      ['👌', 'ok perfeito'],
      ['🤌', 'italiano dedos mão'],
      ['✌️', 'paz vitória'],
      ['🤞', 'dedos cruzados sorte torcendo'],
      ['🤟', 'te amo mão'],
      ['🤘', 'rock chifrinho'],
      ['🤙', 'me liga shaka'],
      ['👈', 'apontando esquerda'],
      ['👉', 'apontando direita'],
      ['👆', 'apontando para cima'],
      ['👇', 'apontando para baixo'],
      ['☝️', 'atenção um dedo'],
      ['✋', 'mão parada pare'],
      ['🖐️', 'mão aberta'],
      ['🖖', 'vulcano spock'],
      ['👋', 'tchau oi acenando'],
      ['🤝', 'aperto de mão acordo negócio'],
      ['🙏', 'obrigado por favor rezando prece'],
      ['✊', 'punho força luta'],
      ['👊', 'soco punho'],
      ['👏', 'palmas aplausos parabéns'],
      ['🙌', 'comemorando mãos para cima aleluia'],
      ['👐', 'mãos abertas'],
      ['🤲', 'mãos juntas pedindo'],
      ['💪', 'força músculo bíceps'],
      ['🧠', 'cérebro inteligente'],
      ['👀', 'olhos olhando vendo'],
      ['👁️', 'olho'],
      ['👄', 'boca lábios'],
      ['🦷', 'dente'],
      ['🙈', 'macaco não vejo vergonha'],
      ['🙉', 'macaco não ouço'],
      ['🙊', 'macaco não falo'],
      ['🤷', 'sei lá ombros dúvida'],
      ['🤦', 'facepalm mão na cara vergonha'],
      ['💁', 'informação atendente'],
      ['🙋', 'levantando a mão eu'],
      ['🙆', 'ok pessoa'],
      ['🙅', 'não pessoa negando'],
      ['🕺', 'dançando homem'],
      ['💃', 'dançando mulher'],
      ['🧘', 'meditando calma ioga'],
      ['🏃', 'correndo'],
      ['🚶', 'andando caminhando'],
      ['👶', 'bebê'],
      ['🧒', 'criança'],
      ['👦', 'menino'],
      ['👧', 'menina'],
      ['👨', 'homem'],
      ['👩', 'mulher'],
      ['🧑', 'pessoa'],
      ['👴', 'velho idoso'],
      ['👵', 'velha idosa'],
      ['👮', 'polícia policial'],
      ['👷', 'obra trabalhador capacete'],
      ['🦸', 'herói super-herói'],
      ['🦹', 'vilão'],
      ['🎅', 'papai noel natal'],
      ['👑', 'coroa rei rainha'],
    ],
  },
  {
    name: 'Bichos e natureza',
    icon: '🐶',
    emojis: [
      ['🐶', 'cachorro cão dog'],
      ['🐱', 'gato gata'],
      ['🐭', 'rato camundongo'],
      ['🐹', 'hamster'],
      ['🐰', 'coelho'],
      ['🦊', 'raposa'],
      ['🐻', 'urso'],
      ['🐼', 'panda'],
      ['🐨', 'coala'],
      ['🐯', 'tigre'],
      ['🦁', 'leão'],
      ['🐮', 'vaca boi'],
      ['🐷', 'porco'],
      ['🐸', 'sapo rã'],
      ['🐵', 'macaco'],
      ['🐔', 'galinha'],
      ['🐧', 'pinguim'],
      ['🐦', 'pássaro'],
      ['🦆', 'pato'],
      ['🦅', 'águia'],
      ['🦉', 'coruja'],
      ['🐺', 'lobo'],
      ['🐗', 'javali'],
      ['🐴', 'cavalo'],
      ['🦄', 'unicórnio'],
      ['🐝', 'abelha'],
      ['🐛', 'lagarta bicho'],
      ['🦋', 'borboleta'],
      ['🐌', 'caracol lesma'],
      ['🐞', 'joaninha'],
      ['🕷️', 'aranha'],
      ['🦂', 'escorpião'],
      ['🐢', 'tartaruga'],
      ['🐍', 'cobra serpente'],
      ['🦎', 'lagartixa lagarto'],
      ['🐙', 'polvo'],
      ['🦑', 'lula'],
      ['🦐', 'camarão'],
      ['🦀', 'caranguejo'],
      ['🐠', 'peixe tropical'],
      ['🐟', 'peixe'],
      ['🐬', 'golfinho'],
      ['🐳', 'baleia'],
      ['🦈', 'tubarão'],
      ['🐊', 'jacaré crocodilo'],
      ['🐅', 'tigre'],
      ['🦓', 'zebra'],
      ['🦍', 'gorila'],
      ['🐘', 'elefante'],
      ['🦏', 'rinoceronte'],
      ['🐪', 'camelo'],
      ['🦒', 'girafa'],
      ['🐄', 'vaca'],
      ['🐕', 'cachorro'],
      ['🐈', 'gato'],
      ['🌵', 'cacto'],
      ['🌲', 'pinheiro árvore'],
      ['🌳', 'árvore'],
      ['🌴', 'coqueiro palmeira praia'],
      ['🌱', 'muda broto planta'],
      ['🌿', 'erva folha'],
      ['🍀', 'trevo sorte'],
      ['🍁', 'folha outono'],
      ['🍂', 'folhas outono'],
      ['🌺', 'flor'],
      ['🌻', 'girassol'],
      ['🌹', 'rosa flor'],
      ['🌷', 'tulipa flor'],
      ['🌸', 'flor de cerejeira'],
      ['🌼', 'margarida flor'],
      ['🌍', 'terra mundo planeta'],
      ['🌞', 'sol'],
      ['🌝', 'lua cheia rosto'],
      ['🌚', 'lua nova rosto'],
      ['⭐', 'estrela'],
      ['🌟', 'estrela brilhando'],
      ['✨', 'brilho brilhos magia'],
      ['⚡', 'raio energia'],
      ['🔥', 'fogo chama top'],
      ['💧', 'gota água'],
      ['🌊', 'onda mar'],
      ['🌈', 'arco-íris'],
      ['☀️', 'sol ensolarado'],
      ['⛅', 'nublado sol nuvem'],
      ['☁️', 'nuvem'],
      ['🌧️', 'chuva'],
      ['⛈️', 'tempestade raio chuva'],
      ['❄️', 'neve floco frio'],
      ['⛄', 'boneco de neve'],
      ['🌪️', 'tornado'],
    ],
  },
  {
    name: 'Comida',
    icon: '🍕',
    emojis: [
      ['🍎', 'maçã fruta'],
      ['🍐', 'pera'],
      ['🍊', 'laranja'],
      ['🍋', 'limão'],
      ['🍌', 'banana'],
      ['🍉', 'melancia'],
      ['🍇', 'uva'],
      ['🍓', 'morango'],
      ['🫐', 'mirtilo'],
      ['🍒', 'cereja'],
      ['🍑', 'pêssego bunda'],
      ['🥭', 'manga'],
      ['🍍', 'abacaxi'],
      ['🥥', 'coco'],
      ['🥝', 'kiwi'],
      ['🍅', 'tomate'],
      ['🥑', 'abacate'],
      ['🥦', 'brócolis'],
      ['🥕', 'cenoura'],
      ['🌽', 'milho'],
      ['🌶️', 'pimenta'],
      ['🥔', 'batata'],
      ['🍞', 'pão'],
      ['🥐', 'croissant'],
      ['🧀', 'queijo'],
      ['🥚', 'ovo'],
      ['🍳', 'ovo frito café da manhã'],
      ['🥓', 'bacon'],
      ['🍔', 'hambúrguer lanche'],
      ['🍟', 'batata frita'],
      ['🍕', 'pizza'],
      ['🌭', 'cachorro-quente hot dog'],
      ['🥪', 'sanduíche'],
      ['🌮', 'taco'],
      ['🌯', 'burrito'],
      ['🥗', 'salada'],
      ['🍝', 'macarrão massa'],
      ['🍜', 'lámen sopa'],
      ['🍲', 'panela ensopado'],
      ['🍛', 'curry arroz'],
      ['🍣', 'sushi'],
      ['🍤', 'camarão frito'],
      ['🍚', 'arroz'],
      ['🥩', 'carne bife churrasco'],
      ['🍗', 'frango coxa'],
      ['🍖', 'carne osso'],
      ['🧁', 'cupcake bolinho'],
      ['🍰', 'bolo fatia'],
      ['🎂', 'bolo de aniversário'],
      ['🍮', 'pudim'],
      ['🍦', 'sorvete casquinha'],
      ['🍨', 'sorvete'],
      ['🍪', 'biscoito cookie'],
      ['🍫', 'chocolate'],
      ['🍬', 'bala doce'],
      ['🍩', 'rosquinha donut'],
      ['🍿', 'pipoca'],
      ['🥜', 'amendoim'],
      ['☕', 'café'],
      ['🍵', 'chá'],
      ['🧃', 'suco caixinha'],
      ['🥤', 'refrigerante copo'],
      ['🍺', 'cerveja chopp'],
      ['🍻', 'cervejas brinde'],
      ['🍷', 'vinho'],
      ['🥂', 'brinde taças comemoração'],
      ['🍸', 'drink coquetel'],
      ['🍹', 'drink tropical'],
      ['🧉', 'chimarrão mate'],
      ['🍾', 'champanhe comemoração'],
      ['🥛', 'leite'],
      ['💊', 'remédio pílula'],
    ],
  },
  {
    name: 'Atividades',
    icon: '🎮',
    emojis: [
      ['⚽', 'futebol bola'],
      ['🏀', 'basquete'],
      ['🏈', 'futebol americano'],
      ['⚾', 'beisebol'],
      ['🎾', 'tênis'],
      ['🏐', 'vôlei'],
      ['🏉', 'rúgbi'],
      ['🎱', 'sinuca bilhar'],
      ['🏓', 'tênis de mesa pingue-pongue'],
      ['🏸', 'badminton'],
      ['🥅', 'gol trave'],
      ['⛳', 'golfe'],
      ['🏹', 'arco e flecha'],
      ['🎣', 'pescaria'],
      ['🥊', 'boxe luva'],
      ['🥋', 'judô karatê'],
      ['⛸️', 'patinação gelo'],
      ['🎿', 'esqui'],
      ['🏂', 'snowboard'],
      ['🏄', 'surfe'],
      ['🏊', 'natação nadando'],
      ['🚴', 'bicicleta ciclismo'],
      ['🏆', 'troféu campeão vitória'],
      ['🥇', 'primeiro lugar ouro medalha'],
      ['🥈', 'segundo lugar prata'],
      ['🥉', 'terceiro lugar bronze'],
      ['🏅', 'medalha'],
      ['🎮', 'videogame controle jogo'],
      ['🕹️', 'joystick arcade'],
      ['🎲', 'dado sorte'],
      ['🎯', 'alvo mira acertou'],
      ['🎰', 'caça-níquel sorte'],
      ['🃏', 'coringa carta'],
      ['🎴', 'cartas'],
      ['🎭', 'teatro máscaras'],
      ['🎨', 'arte pintura'],
      ['🎬', 'cinema claquete filme'],
      ['🎤', 'microfone cantar karaokê'],
      ['🎧', 'fone de ouvido'],
      ['🎵', 'música nota'],
      ['🎶', 'música notas'],
      ['🎸', 'guitarra violão'],
      ['🥁', 'bateria tambor'],
      ['🎹', 'piano teclado'],
      ['🎺', 'trompete'],
      ['🎻', 'violino'],
      ['🪕', 'banjo cavaquinho'],
      ['🎪', 'circo'],
      ['🎉', 'festa comemoração parabéns'],
      ['🎊', 'confete festa'],
      ['🎈', 'balão festa'],
      ['🎁', 'presente'],
      ['🎃', 'halloween abóbora'],
      ['🎄', 'natal árvore'],
      ['🧨', 'fogos explosivo'],
    ],
  },
  {
    name: 'Lugares',
    icon: '🚗',
    emojis: [
      ['🚗', 'carro'],
      ['🚕', 'táxi'],
      ['🚙', 'suv carro'],
      ['🚌', 'ônibus'],
      ['🏎️', 'corrida fórmula 1'],
      ['🚓', 'viatura polícia'],
      ['🚑', 'ambulância'],
      ['🚒', 'bombeiros caminhão'],
      ['🚚', 'caminhão'],
      ['🚜', 'trator'],
      ['🛵', 'moto scooter'],
      ['🏍️', 'moto'],
      ['🚲', 'bicicleta'],
      ['🛴', 'patinete'],
      ['✈️', 'avião viagem'],
      ['🚀', 'foguete decolar'],
      ['🛸', 'disco voador óvni'],
      ['🚁', 'helicóptero'],
      ['⛵', 'veleiro barco'],
      ['🚢', 'navio'],
      ['🚂', 'trem locomotiva'],
      ['🚇', 'metrô'],
      ['🗺️', 'mapa'],
      ['🏠', 'casa'],
      ['🏡', 'casa jardim'],
      ['🏢', 'prédio escritório'],
      ['🏥', 'hospital'],
      ['🏦', 'banco'],
      ['🏨', 'hotel'],
      ['🏫', 'escola'],
      ['🏭', 'fábrica'],
      ['⛪', 'igreja'],
      ['🕌', 'mesquita'],
      ['🏟️', 'estádio'],
      ['🗽', 'estátua da liberdade nova york'],
      ['🗼', 'torre tóquio'],
      ['🗿', 'moai ilha de páscoa'],
      ['🏰', 'castelo'],
      ['⛲', 'chafariz fonte'],
      ['⛺', 'barraca acampamento'],
      ['🏖️', 'praia'],
      ['🏔️', 'montanha'],
      ['🌋', 'vulcão'],
      ['🏜️', 'deserto'],
      ['🌉', 'ponte noite'],
      ['🌃', 'cidade noite'],
      ['🌆', 'cidade pôr do sol'],
      ['🎡', 'roda-gigante'],
      ['🎢', 'montanha-russa'],
    ],
  },
  {
    name: 'Objetos',
    icon: '💻',
    emojis: [
      ['💻', 'computador notebook'],
      ['🖥️', 'computador monitor'],
      ['⌨️', 'teclado'],
      ['🖱️', 'mouse'],
      ['🖨️', 'impressora'],
      ['📱', 'celular telefone'],
      ['☎️', 'telefone'],
      ['📞', 'telefone ligação'],
      ['📷', 'câmera foto'],
      ['📹', 'câmera vídeo'],
      ['🎥', 'filmadora'],
      ['📺', 'televisão tv'],
      ['📻', 'rádio'],
      ['🔋', 'bateria'],
      ['🔌', 'tomada energia'],
      ['💡', 'lâmpada ideia'],
      ['🔦', 'lanterna'],
      ['🕯️', 'vela'],
      ['💰', 'dinheiro saco'],
      ['💵', 'dinheiro nota'],
      ['💳', 'cartão de crédito'],
      ['💎', 'diamante joia'],
      ['⚖️', 'balança justiça'],
      ['🔧', 'chave inglesa ferramenta'],
      ['🔨', 'martelo'],
      ['🪛', 'chave de fenda'],
      ['🔩', 'parafuso'],
      ['⚙️', 'engrenagem configuração'],
      ['🧲', 'ímã'],
      ['🔫', 'arma pistola'],
      ['💣', 'bomba'],
      ['🔪', 'faca'],
      ['🛡️', 'escudo proteção'],
      ['🚪', 'porta'],
      ['🛏️', 'cama'],
      ['🛋️', 'sofá'],
      ['🚽', 'privada banheiro'],
      ['🚿', 'chuveiro banho'],
      ['🧹', 'vassoura limpeza'],
      ['🧺', 'cesto roupa'],
      ['🔑', 'chave'],
      ['🔒', 'cadeado trancado'],
      ['🔓', 'cadeado aberto'],
      ['📦', 'caixa pacote'],
      ['📬', 'correio caixa de correio'],
      ['📝', 'anotação escrever'],
      ['📄', 'documento papel'],
      ['📊', 'gráfico barras'],
      ['📈', 'gráfico subindo alta'],
      ['📉', 'gráfico caindo queda'],
      ['📅', 'calendário data'],
      ['📌', 'alfinete fixar'],
      ['📎', 'clipe anexo'],
      ['✂️', 'tesoura recortar'],
      ['📚', 'livros estudo'],
      ['📖', 'livro aberto leitura'],
      ['✏️', 'lápis escrever'],
      ['🖊️', 'caneta'],
      ['🔍', 'lupa procurar busca'],
      ['⏰', 'despertador alarme'],
      ['⌛', 'ampulheta tempo'],
      ['⏳', 'ampulheta esperando'],
      ['🧭', 'bússola'],
      ['🌡️', 'termômetro temperatura'],
      ['💉', 'seringa vacina injeção'],
      ['🧪', 'tubo de ensaio experimento'],
      ['🔬', 'microscópio ciência'],
      ['🔭', 'telescópio'],
      ['🧬', 'dna'],
      ['🩹', 'curativo band-aid'],
      ['🧯', 'extintor'],
      ['🛒', 'carrinho compras'],
      ['👕', 'camiseta roupa'],
      ['👖', 'calça jeans'],
      ['👗', 'vestido'],
      ['👟', 'tênis sapato'],
      ['🧢', 'boné'],
      ['🎒', 'mochila'],
      ['👓', 'óculos'],
      ['⌚', 'relógio pulso'],
    ],
  },
  {
    name: 'Símbolos',
    icon: '❤️',
    emojis: [
      ['❤️', 'coração vermelho amor'],
      ['🧡', 'coração laranja'],
      ['💛', 'coração amarelo'],
      ['💚', 'coração verde'],
      ['💙', 'coração azul'],
      ['💜', 'coração roxo'],
      ['🖤', 'coração preto'],
      ['🤍', 'coração branco'],
      ['🤎', 'coração marrom'],
      ['💔', 'coração partido'],
      ['❣️', 'coração exclamação'],
      ['💕', 'dois corações amor'],
      ['💞', 'corações girando'],
      ['💓', 'coração batendo'],
      ['💗', 'coração crescendo'],
      ['💖', 'coração brilhando'],
      ['💘', 'coração flecha cupido'],
      ['💝', 'coração presente'],
      ['💯', 'cem nota máxima top'],
      ['✅', 'certo feito confirmado'],
      ['☑️', 'marcado caixa'],
      ['✔️', 'certo confirmado'],
      ['❌', 'errado x não'],
      ['⭕', 'círculo certo'],
      ['❗', 'exclamação atenção'],
      ['❓', 'interrogação dúvida'],
      ['⚠️', 'aviso atenção perigo'],
      ['🚫', 'proibido'],
      ['🔞', 'proibido menores'],
      ['♻️', 'reciclagem'],
      ['🔔', 'sino notificação'],
      ['🔕', 'sino cortado silenciado'],
      ['🔇', 'mudo sem som'],
      ['🔊', 'som alto volume'],
      ['📢', 'megafone anúncio'],
      ['💬', 'balão de fala mensagem'],
      ['💭', 'balão de pensamento'],
      ['🗯️', 'balão de raiva'],
      ['♠️', 'espadas carta'],
      ['♥️', 'copas carta'],
      ['♦️', 'ouros carta'],
      ['♣️', 'paus carta'],
      ['🆗', 'ok'],
      ['🆕', 'novo'],
      ['🆓', 'grátis free'],
      ['🔴', 'círculo vermelho ao vivo'],
      ['🟠', 'círculo laranja'],
      ['🟡', 'círculo amarelo'],
      ['🟢', 'círculo verde online'],
      ['🔵', 'círculo azul'],
      ['⚫', 'círculo preto'],
      ['⚪', 'círculo branco'],
      ['🟥', 'quadrado vermelho'],
      ['🟩', 'quadrado verde'],
      ['🟦', 'quadrado azul'],
      ['⬛', 'quadrado preto'],
      ['⬜', 'quadrado branco'],
      ['🔶', 'losango laranja'],
      ['🔷', 'losango azul'],
      ['♾️', 'infinito'],
      ['➕', 'mais soma'],
      ['➖', 'menos subtração'],
      ['✖️', 'vezes multiplicação'],
      ['➗', 'dividir divisão'],
      ['🔝', 'topo top'],
      ['🔙', 'voltar'],
      ['⏩', 'avançar rápido'],
      ['⏪', 'voltar rápido'],
      ['▶️', 'play tocar'],
      ['⏸️', 'pausa'],
      ['⏹️', 'parar stop'],
      ['⏺️', 'gravar'],
      ['🔀', 'aleatório embaralhar'],
      ['🔁', 'repetir loop'],
      ['🔄', 'atualizar recarregar'],
    ],
  },
];

/** "Ã" → "a": deixa a busca funcionar sem acento ("acucar" acha "açúcar"). */
function normalize(text: string) {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '');
}

/** Emojis cujo nome ou palavras-chave batem com o que foi digitado. */
export function searchEmojis(query: string): string[] {
  const terms = normalize(query).split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  const found: string[] = [];
  for (const group of EMOJI_GROUPS) {
    for (const [char, keywords] of group.emojis) {
      const haystack = normalize(`${keywords} ${group.name}`);
      if (terms.every((term) => haystack.includes(term))) found.push(char);
    }
  }
  return found;
}

/** A descrição que aparece no rodapé do painel quando o mouse passa por cima. */
export function emojiLabel(char: string): string {
  for (const group of EMOJI_GROUPS) {
    const found = group.emojis.find(([c]) => c === char);
    if (found) return found[1].split(' ')[0];
  }
  return char;
}
